# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfada555ad4622c4919434b6c11308f56899a2cffe40d6f035d8ff66afcb1530c053e84345cc03c61bad75616c71fa9f9de637882e60459986e2093f19863ee9

test:
  secret_key_base: 32c827539e1761853a5aa630216b682f54d43598c1e22daf9db7c6c66be264f70556663f0d731e5b0e7cb81851e1806f059a5d7c2db02ab6a5a4834abfb29a18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
